/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Casa as PrismaCasa } from "@prisma/client";

export class CasaServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CasaCountArgs, "select">): Promise<number> {
    return this.prisma.casa.count(args);
  }

  async casas(args: Prisma.CasaFindManyArgs): Promise<PrismaCasa[]> {
    return this.prisma.casa.findMany(args);
  }
  async casa(args: Prisma.CasaFindUniqueArgs): Promise<PrismaCasa | null> {
    return this.prisma.casa.findUnique(args);
  }
  async createCasa(args: Prisma.CasaCreateArgs): Promise<PrismaCasa> {
    return this.prisma.casa.create(args);
  }
  async updateCasa(args: Prisma.CasaUpdateArgs): Promise<PrismaCasa> {
    return this.prisma.casa.update(args);
  }
  async deleteCasa(args: Prisma.CasaDeleteArgs): Promise<PrismaCasa> {
    return this.prisma.casa.delete(args);
  }
}
