/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Casa } from "./Casa";
import { CasaCountArgs } from "./CasaCountArgs";
import { CasaFindManyArgs } from "./CasaFindManyArgs";
import { CasaFindUniqueArgs } from "./CasaFindUniqueArgs";
import { CreateCasaArgs } from "./CreateCasaArgs";
import { UpdateCasaArgs } from "./UpdateCasaArgs";
import { DeleteCasaArgs } from "./DeleteCasaArgs";
import { CasaService } from "../casa.service";
@graphql.Resolver(() => Casa)
export class CasaResolverBase {
  constructor(protected readonly service: CasaService) {}

  async _casasMeta(
    @graphql.Args() args: CasaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Casa])
  async casas(@graphql.Args() args: CasaFindManyArgs): Promise<Casa[]> {
    return this.service.casas(args);
  }

  @graphql.Query(() => Casa, { nullable: true })
  async casa(@graphql.Args() args: CasaFindUniqueArgs): Promise<Casa | null> {
    const result = await this.service.casa(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Casa)
  async createCasa(@graphql.Args() args: CreateCasaArgs): Promise<Casa> {
    return await this.service.createCasa({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Casa)
  async updateCasa(@graphql.Args() args: UpdateCasaArgs): Promise<Casa | null> {
    try {
      return await this.service.updateCasa({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Casa)
  async deleteCasa(@graphql.Args() args: DeleteCasaArgs): Promise<Casa | null> {
    try {
      return await this.service.deleteCasa(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
