/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CasaService } from "../casa.service";
import { CasaCreateInput } from "./CasaCreateInput";
import { Casa } from "./Casa";
import { CasaFindManyArgs } from "./CasaFindManyArgs";
import { CasaWhereUniqueInput } from "./CasaWhereUniqueInput";
import { CasaUpdateInput } from "./CasaUpdateInput";

export class CasaControllerBase {
  constructor(protected readonly service: CasaService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Casa })
  async createCasa(@common.Body() data: CasaCreateInput): Promise<Casa> {
    return await this.service.createCasa({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Casa] })
  @ApiNestedQuery(CasaFindManyArgs)
  async casas(@common.Req() request: Request): Promise<Casa[]> {
    const args = plainToClass(CasaFindManyArgs, request.query);
    return this.service.casas({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Casa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async casa(
    @common.Param() params: CasaWhereUniqueInput
  ): Promise<Casa | null> {
    const result = await this.service.casa({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Casa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCasa(
    @common.Param() params: CasaWhereUniqueInput,
    @common.Body() data: CasaUpdateInput
  ): Promise<Casa | null> {
    try {
      return await this.service.updateCasa({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Casa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCasa(
    @common.Param() params: CasaWhereUniqueInput
  ): Promise<Casa | null> {
    try {
      return await this.service.deleteCasa({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
